--Escenario previo a poder crear etapa
--OFICINAREGIONALEPS inicial
INSERT INTO "OFICINAREGIONALEPS" (NOMBREEPS, REGIONEPS)
VALUES ('Saludmás', 1);
--ESTADOVACUNACION inicial
INSERT INTO "ESTADOVACUNACION" (IDENTIFICADORESTADO, DESCRIPCIONESTADO )
VALUES (1,'Pendiente de asignación');
--ETAPA inicial
INSERT INTO "ETAPA" (NUMERODEETAPA, DESCRIPCIONETAPA )
VALUES (1,'Fase 1- Etapa 1');
--PUNTOVACUNACION inicial
INSERT INTO "PUNTOVACUNACION" (DIRECCIONPUNTOVACUNACION, NOMBREPUNTOVACUNACION,CAPACIDADSIMULTANEA,CAPACIDADDIARIA,DISPONIBILIDADDEDOSIS, NOMBREOFICINA,REGIONOFICINA)
VALUES ('CR 11','Centro vacunación Saludmás',300,200,10000,'Saludmás', 1);
--CIUDADANO inicial
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA )
VALUES ('CC','1', 'Juan','Perez', '1' , TO_DATE('2000/12/1', 'YY/MM/DD'), 324789 , 1, 1,'CR 11', 'Saludmás', 1);

--Pruebas unicidad
--PK inexistente
INSERT INTO "ETAPA" (NUMERODEETAPA, DESCRIPCIONETAPA )
VALUES (1,'Fase 1- Etapa 1');

--PK existente
INSERT INTO "ETAPA" (NUMERODEETAPA, DESCRIPCIONETAPA )
VALUES (2,'Fase 1- Etapa 2');

--Pruebas integridad FK
--Agregar ciudadano con etapa válida
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA )
VALUES ('CC','2', 'Juan','Perez', '1' , TO_DATE('2000/12/1', 'YY/MM/DD'), 324789 , 1, 1,'CR 11', 'Saludmás', 1);

--Agregar ciudadano con etapa inválida
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA )
VALUES ('CC','3', 'Juan','Perez', '1' , TO_DATE('2000/12/1', 'YY/MM/DD'), 324789 , 1, 5,'CR 11', 'Saludmás', 1);

--Borrar tupla dependiente
DELETE FROM ETAPA;

--Pruebas integridad CK
--Se cumple CK
INSERT INTO "ETAPA" (NUMERODEETAPA, DESCRIPCIONETAPA )
VALUES (3,'Fase 1- Etapa 3');
