--En caso de querer limpiar tablas
DELETE FROM cita;
DELETE FROM talentohumano;
DELETE FROM pertenecea;
DELETE FROM condicion;
DELETE FROM trabajaen;
DELETE FROM ciudadano;
DELETE FROM puntovacunacion;
DELETE FROM lotevacuna;
DELETE FROM oficinaregionaleps;
DELETE FROM estadovacunacion;
DELETE FROM etapa;

--Escenario previo a poder crear CONDICION
--OFICINAREGIONALEPS inicial
INSERT INTO "OFICINAREGIONALEPS" (NOMBREEPS, REGIONEPS)
VALUES ('Saludmás', 1);
--ESTADOVACUNACION inicial
INSERT INTO "ESTADOVACUNACION" (IDENTIFICADORESTADO, DESCRIPCIONESTADO )
VALUES (1,'Pendiente de asignación');
--ETAPA inicial
INSERT INTO "ETAPA" (NUMERODEETAPA, DESCRIPCIONETAPA )
VALUES (1,'Fase 1- Etapa 1');
--PUNTOVACUNACION inicial
INSERT INTO "PUNTOVACUNACION" (DIRECCIONPUNTOVACUNACION, NOMBREPUNTOVACUNACION,CAPACIDADSIMULTANEA,CAPACIDADDIARIA,DISPONIBILIDADDEDOSIS, NOMBREOFICINA,REGIONOFICINA)
VALUES ('CR 11','Centro vacunación Saludmás',300,200,10000,'Saludmás', 1);
--CIUDADANO inicial
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA )
VALUES ('CC','1', 'Juan','Perez', '1' , TO_DATE('2000/12/1', 'YY/MM/DD'), 324789 , 1, 1,'CR 11', 'Saludmás', 1);

--Pruebas unicidad
--PK nueva
INSERT INTO "CONDICION" (IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES(3, 'Practicante de medicina');

--PK existente
INSERT INTO "CONDICION" (IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES(3, 'Practicante de medicina');

--Pruebas integridad FK
--Agregar a PERTENECEA
INSERT INTO "PERTENECEA" (TIPOIDCIUDADANO, IDCIUDADANO, IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES('CC','1', 3, 'Practicante de medicina');

--Agregar ya existente a PERTENECEA
INSERT INTO "PERTENECEA" (TIPOIDCIUDADANO, IDCIUDADANO, IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES('CC','1', 3, 'Practicante de medicina');

--Eliminar tupla maestra
DELETE FROM CONDICION;

--Pruebas integridad CK
--Se cumple CK
INSERT INTO "CONDICION" (IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES(5, 'Menor de 20 años');
