DELETE FROM cita;
DELETE FROM talentohumano;
DELETE FROM pertenecea;
DELETE FROM condicion;
DELETE FROM trabajaen;
DELETE FROM ciudadano;
DELETE FROM puntovacunacion;
DELETE FROM lotevacuna;
DELETE FROM oficinaregionaleps;
DELETE FROM estadovacunacion;
DELETE FROM etapa;

--Escenario previo a poder crear PERTENECEA
--OFICINAREGIONALEPS inicial
INSERT INTO "OFICINAREGIONALEPS" (NOMBREEPS, REGIONEPS)
VALUES ('Saludmás', 1);
--ESTADOVACUNACION inicial
INSERT INTO "ESTADOVACUNACION" (IDENTIFICADORESTADO, DESCRIPCIONESTADO )
VALUES (1,'Pendiente de asignación');
--ETAPA inicial
INSERT INTO "ETAPA" (NUMERODEETAPA, DESCRIPCIONETAPA )
VALUES (1,'Fase 1- Etapa 1');
--PUNTOVACUNACION inicial
INSERT INTO "PUNTOVACUNACION" (DIRECCIONPUNTOVACUNACION, NOMBREPUNTOVACUNACION,CAPACIDADSIMULTANEA,CAPACIDADDIARIA,DISPONIBILIDADDEDOSIS, NOMBREOFICINA,REGIONOFICINA)
VALUES ('CR 11','Centro vacunación Saludmás',300,200,10000,'Saludmás', 1);
--CIUDADANO inicial
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA )
VALUES ('CC','1', 'Juan','Perez', '1' , TO_DATE('2000/12/1', 'YY/MM/DD'), 324789 , 1, 1,'CR 11', 'Saludmás', 1);
--CIUDADANO inicial
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA )
VALUES ('CC','2', 'Juan','Perez', '1' , TO_DATE('2000/12/1', 'YY/MM/DD'), 324789 , 1, 1,'CR 11', 'Saludmás', 1);

--CONDICION inicial
INSERT INTO "CONDICION" (IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES(3, 'Practicante de medicina');

--Pruebas unicidad
--PK inexistente
INSERT INTO "PERTENECEA" (TIPOIDCIUDADANO, IDCIUDADANO, IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES('CC','1', 3, 'Practicante de medicina');

--PK existente
INSERT INTO "PERTENECEA" (TIPOIDCIUDADANO, IDCIUDADANO, IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES('CC','1', 3, 'Practicante de medicina');

--Pruebas interidad FK
--FK inexistente
INSERT INTO "PERTENECEA" (TIPOIDCIUDADANO, IDCIUDADANO, IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES('CC','2', 3, 'Practicante de medicina');

--FK inexistente
INSERT INTO "PERTENECEA" (TIPOIDCIUDADANO, IDCIUDADANO, IDENTIFICADORCONDICION, DESCRIPCIONCONDICION)
VALUES('CC','2', 4, 'Practicante de psicología');

--Borrado de tuplas 
DELETE FROM CONDICION;
