--En caso de querer limpiar tablas
DELETE FROM cita;
DELETE FROM talentohumano;
DELETE FROM pertenecea;
DELETE FROM condicion;
DELETE FROM trabajaen;
DELETE FROM tienecondicionpreservacion;
DELETE FROM condicionpreservacion;
DELETE FROM tieneinfraestructura;
DELETE FROM infraestructura;
DELETE FROM puntovacunacionvirtual;
DELETE FROM vacuna;
DELETE FROM ciudadano;
DELETE FROM puntovacunacion;
DELETE FROM lotevacuna;
DELETE FROM oficinaregionaleps;
DELETE FROM estadovacunacion;
DELETE FROM etapa;

--Datos oficinaRegional
--Punto inicial
INSERT INTO "OFICINAREGIONALEPS" (NOMBREEPS, REGIONEPS)
VALUES ('Compensar', 1);

--Datos PuntoVacunacion
--Punto inicial
INSERT INTO "PUNTOVACUNACION" (DIRECCIONPUNTOVACUNACION, NOMBREPUNTOVACUNACION,CAPACIDADSIMULTANEA,CAPACIDADDIARIA,DISPONIBILIDADDEDOSIS, NOMBREOFICINA,REGIONOFICINA, SoloMayores, SoloSalud, EstaHabilitado)
VALUES ('Cll 1','Centro atención Compensar 1',0,2,2,'Compensar',1, 0, 0, 1);

--Estado vacunacion
INSERT INTO "ESTADOVACUNACION" (IDENTIFICADORESTADO, DESCRIPCIONESTADO )
VALUES (1,'No vacunado');

--Etapa
INSERT INTO "ETAPA" (NUMERODEETAPA, DESCRIPCIONETAPA )
VALUES (5,'Etapa 5');

--CIUDADANO
--Datos Ciudadanos
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','1', 'Juan','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Masculino', 'Ciudadano', 'Bogotá', 'Suba');
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','2', 'Rafael','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Masculino', 'Ciudadano', 'Bogotá', 'Suba');
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','3', 'Sol','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Femenino', 'Ciudadano', 'Bogotá', 'Suba');
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','4', 'Irene','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Femenino', 'Ciudadano', 'Bogotá', 'Suba');
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','5', 'María','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Femenino', 'Ciudadano', 'Bogotá', 'Suba');

--Citas
INSERT INTO "CITA" (IDENTIFICADORCITA, FECHACITA, TIPOIDCIUDADANO,IDCIUDADANO)
VALUES(1, TO_TIMESTAMP('10-SEP-2021:10:10','DD-MON-RRHH24:MI:SS'),'CC','1');
INSERT INTO "CITA" (IDENTIFICADORCITA, FECHACITA, TIPOIDCIUDADANO,IDCIUDADANO)
VALUES(2, TO_TIMESTAMP('10-SEP-2021:10:10','DD-MON-RRHH24:MI:SS'),'CC','2');
INSERT INTO "CITA" (IDENTIFICADORCITA, FECHACITA, TIPOIDCIUDADANO,IDCIUDADANO)
VALUES(3, TO_TIMESTAMP('10-SEP-2021:10:10','DD-MON-RRHH24:MI:SS'),'CC','3');

--LoteVacuna
INSERT INTO "LOTEVACUNA" (IDENTIFICADORLOTE, NOMBREOFICINA,REGIONOFICINA)
VALUES (1,'Compensar', 1);

--Vacunas
INSERT INTO "VACUNA" (IDENTIFICADORVACUNA, HASIDOAPLICADO, LOTEVACUNA, PUNTOVACUNACION, TIPOIDCIUDADANO, IDCIUDADANO, Tecnologia)
VALUES (1,'1',1,'Cll 1','CC','1', 'Virus desactivado');
INSERT INTO "VACUNA" (IDENTIFICADORVACUNA, HASIDOAPLICADO, LOTEVACUNA, PUNTOVACUNACION, TIPOIDCIUDADANO, IDCIUDADANO, Tecnologia )
VALUES (2,'1',1,'Cll 1','CC','2', 'Virus desactivado');
INSERT INTO "VACUNA" (IDENTIFICADORVACUNA, HASIDOAPLICADO, LOTEVACUNA, PUNTOVACUNACION, TIPOIDCIUDADANO, IDCIUDADANO, Tecnologia )
VALUES (3,'0',1,'Cll 1','CC','3', 'Virus desactivado');

--Evacuacion de ciudadanos que no han sido vacunados y punto de vacunacion deshabilitado
UPDATE PUNTOVACUNACION
SET estahabilitado = 0
WHERE direccionpuntovacunacion = 'Cll 1';

UPDATE CIUDADANO c
SET c.puntovacunacion = NULL
WHERE c.puntovacunacion = 'Cll 1' AND
     (c.tipodeidentificacion, c.identificacionciudadano) NOT IN
     (SELECT tipodeidentificacion, identificacionciudadano
      FROM Ciudadano c, Cita cit, Vacuna v
      WHERE c.tipodeidentificacion = cit.tipoidciudadano AND
            c.identificacionciudadano = cit.idciudadano AND
            c.tipodeidentificacion = v.tipoidciudadano AND
            c.identificacionciudadano = v.idciudadano AND
            v.hasidoaplicado = '1');

UPDATE PUNTOVACUNACION
SET CapacidadSimultanea = CapacidadSimultanea + 3
WHERE direccionpuntovacunacion = 'Cll 1';

COMMIT;
