--En caso de querer limpiar tablas
DELETE FROM cita;
DELETE FROM talentohumano;
DELETE FROM pertenecea;
DELETE FROM condicion;
DELETE FROM trabajaen;
DELETE FROM tienecondicionpreservacion;
DELETE FROM condicionpreservacion;
DELETE FROM tieneinfraestructura;
DELETE FROM infraestructura;
DELETE FROM puntovacunacionvirtual;
DELETE FROM vacuna;
DELETE FROM ciudadano;
DELETE FROM puntovacunacion;
DELETE FROM lotevacuna;
DELETE FROM oficinaregionaleps;
DELETE FROM estadovacunacion;
DELETE FROM etapa;

--Datos oficinaRegional
--Punto inicial
INSERT INTO "OFICINAREGIONALEPS" (NOMBREEPS, REGIONEPS)
VALUES ('Compensar', 1);

--Datos PuntoVacunacion
--Punto inicial
INSERT INTO "PUNTOVACUNACION" (DIRECCIONPUNTOVACUNACION, NOMBREPUNTOVACUNACION,CAPACIDADSIMULTANEA,CAPACIDADDIARIA,DISPONIBILIDADDEDOSIS, NOMBREOFICINA,REGIONOFICINA, SoloMayores, SoloSalud, EstaHabilitado)
VALUES ('Cll 1','Centro atención Compensar 1',5,2,2,'Compensar',1, 0, 0, 1);

--Punto de solo mayores y solo salud
INSERT INTO "PUNTOVACUNACION" (DIRECCIONPUNTOVACUNACION, NOMBREPUNTOVACUNACION,CAPACIDADSIMULTANEA,CAPACIDADDIARIA,DISPONIBILIDADDEDOSIS, NOMBREOFICINA,REGIONOFICINA, SoloMayores, SoloSalud, EstaHabilitado)
VALUES ('Cll 2','Centro atención Compensar 1',5,2,2,'Compensar',1, 1, 1, 1);

--Estado vacunacion
INSERT INTO "ESTADOVACUNACION" (IDENTIFICADORESTADO, DESCRIPCIONESTADO )
VALUES (1,'No vacunado');

--Etapa
INSERT INTO "ETAPA" (NUMERODEETAPA, DESCRIPCIONETAPA )
VALUES (5,'Etapa 5');

--CIUDADANO
--Asignacion a puntos
--Datos Ciudadanos
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','1', 'Juan','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Masculino', 'Ciudadano', 'Bogotá', 'Suba');

UPDATE PUNTOVACUNACION
SET CAPACIDADSIMULTANEA  = CAPACIDADSIMULTANEA - 1
WHERE direccionpuntovacunacion = 'Cll 1';

INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','2', 'Rafael','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Masculino', 'Ciudadano', 'Bogotá', 'Suba');

UPDATE PUNTOVACUNACION
SET CAPACIDADSIMULTANEA  = CAPACIDADSIMULTANEA - 1
WHERE direccionpuntovacunacion = 'Cll 1';

INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','3', 'Sol','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Femenino', 'Ciudadano', 'Bogotá', 'Suba');

UPDATE PUNTOVACUNACION
SET CAPACIDADSIMULTANEA  = CAPACIDADSIMULTANEA - 1
WHERE direccionpuntovacunacion = 'Cll 1';

INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','4', 'Irene','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Femenino', 'Ciudadano', 'Bogotá', 'Suba');

UPDATE PUNTOVACUNACION
SET CAPACIDADSIMULTANEA  = CAPACIDADSIMULTANEA - 1
WHERE direccionpuntovacunacion = 'Cll 1';

INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','5', 'María','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Femenino', 'Ciudadano', 'Bogotá', 'Suba');

--Escenario 1.1
INSERT INTO "CIUDADANO" (TIPODEIDENTIFICACION, IDENTIFICACIONCIUDADANO, NOMBRECIUDADANO, APELLIDOCIUDADANO, ESVACUNABLE, FECHADENACIMIENTO, TELEFONODECONTACTO, ESTADOVACUNACION, ETAPA, PUNTOVACUNACION, NOMBREOFICINA, REGIONOFICINA, Genero, Rol, Ciudad, Localidad)
VALUES ('CC','6', 'Olga','Perez', '1' , TO_DATE('1998/11/1', 'YY/MM/DD'), 23875496 , 1, 5,'Cll 1', 'Compensar', 1 , 'Femenino', 'Ciudadano', 'Bogotá', 'Suba');

UPDATE PUNTOVACUNACION
SET CAPACIDADSIMULTANEA  = CAPACIDADSIMULTANEA - 1
WHERE direccionpuntovacunacion = 'Cll 1';


--Escenario 2: Desde la interfaz se agrega al punto a cualquier ciudadano de los que exiten, no se agrega
--Escenario 3: Desde la interfaz se agrega al punto a cualquier ciudadano de los que exiten, no se agrega
